# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - mvcquickstart

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      
      - name: directory listing
        run: |
          ls -R .

      - name: Generate EF migration script
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool restore

      # - name: Add dotnet tools to PATH
      #   run: |
      #     echo $env.path
      #     echo ${{env.DOTNET_ROOT}}/tools | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
      
      - name: update db
        run: |
          echo $env.path
          dotnet ef
          ls ${{env.DOTNET_ROOT}}\tools
          dotnet ef migrations
          dotnet ef migrations script
          dotnet ef migrations script --idempotent --startup-project mvc.csproj --output ${{env.DOTNET_ROOT}}/myapp/migrate.sql

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: self-hosted
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mvcquickstart'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5074982B7F5D4A9D9484B42AD737236D }}
          package: .
        
      - name: directory listing
        run: |
          ls -R .
      
      - name: Apply EF migration script
        uses: Azure/sql-action@v1.2
        with:
          connection-string: ${{ secrets.MOVIE_CONNECTION_STRING }}
          sql-file: ./migrate.sql
        
